drop table cmiAlmacenes
drop table cmiCalidadProceso
drop table cmiCategorias
drop table cmiClientes
drop table cmiDepartamentos
drop table cmiDetallesRequisicion
drop table cmiEstatus
drop table cmiEtapas
drop table cmiGrupos
drop table cmiMarcas
drop table cmiMateriales
drop table cmiModulos
drop table cmiOrigenesRequisicion
drop table cmiPermisos
drop table cmiPlanosDespiece
drop table cmiPlanosMontaje
drop table cmiProcesos
drop table cmiProyectos
drop table cmiRequerimientos
drop table cmiRequisiciones
drop table cmiRutasFabricacion
drop table cmiSubMarcas
drop table cmiTiposCalidad
drop table cmiTiposConstruccion
drop table cmiTiposMaterial
drop table cmiTiposMovtoMaterial
drop table cmiTiposProceso
drop table cmiUnidadesMedida
drop table cmiUsuarios
